version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.2
    container_name: apm-server
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - setup.kibana.host="kibana:5601"
    depends_on:
      - elasticsearch
    ports:
      - "8200:8200" # APM Server listens on port 8200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel.yaml" ]
    volumes:
      - ./.config/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" 
  
  rolldice:
    image: rolldice:v1
    build:
      context: examples/java
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
