apiVersion: v1
data:
  otel.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317" # Bind to all interfaces on port 4317 for gRPC
          http:
            endpoint: "0.0.0.0:4318" # Optional: Bind to all interfaces on port 4318 for HTTP

    processors:
      batch:
        timeout: 10s
        send_batch_size: 100

    exporters:
      # Debug Exporter (replaces the deprecated logging exporter)
      debug:
        verbosity: detailed # Options: basic, normal, detailed

        #otlp/elastic:
        #endpoint: "http://apm-server:8200" # Replace with your APM Server URL
        #tls:
        #  insecure: true # Set to false and configure certificates if using TLS

      elasticsearch:
        endpoints: [ "http://elasticsearch:9200" ]
        #index: "otel-logs-%{+yyyy.MM.dd}"
        tls:
          insecure: true # Set to false and configure certificates if using TLS

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: otel-collector
  name: otel-collector-cm0
